# GENERATED by ggen_igniter from the admitted ex4pmal:RegisteredAlgorithm graph. Do not edit.
defmodule Ex4pmEngine.Wasm.AlgoRegistryTest do
  use ExUnit.Case, async: true

  alias Ex4pmEngine.Wasm.{AlgoRegistry, RealTransport}

  @expected_ids [
      :align,
      :allen_temporal,
      :bayesian,
      :conform,
      :ctl_check,
      :discover,
      :dot_product,
      :etc_precision,
      :euclidean_distance,
      :ewma,
      :forecast,
      :holt_forecast,
      :htn_plan,
      :ks_critical_value,
      :ks_statistic,
      :markov,
      :mean,
      :median,
      :oc_discover,
      :ocpq_eval,
      :optimize,
      :percentile,
      :playout,
      :powl_mine,
      :prolog_query,
      :regression,
      :simulate,
      :soundness,
      :standardize,
      :std_deviation,
      :strips_plan,
      :survival,
      :trend_classify
  ]

  @ladder ~w(UNKNOWN OBSERVED VALIDATED DERIVED CANDIDATE EXPERIMENTALLY_SUPPORTED ADMITTED
             MANUFACTURED ACTUATED VERIFIED)

  test "registry count equals the ontology's registered-algorithm rows (33)" do
    assert length(AlgoRegistry.algo_specs()) == 33
    assert AlgoRegistry.algorithm_ids() == @expected_ids
  end

  test "algorithm ids are unique and sorted" do
    ids = AlgoRegistry.algorithm_ids()
    assert ids == Enum.uniq(ids)
    assert ids == Enum.sort(ids)
  end

  test "every registered module is loadable and declares the registered export names" do
    for spec <- AlgoRegistry.algo_specs() do
      assert Code.ensure_loaded?(spec.module), "#{inspect(spec.module)} is not loadable"
      assert function_exported?(spec.module, :wasm_export, 0)
      assert spec.module.wasm_export() == spec.export_name
      assert spec.module.wasm_replay_export() == spec.replay_export_name
      assert spec.export_name == "wasm4pm_ex4pm_#{spec.algorithm_id}_v1"
      assert spec.replay_export_name == "wasm4pm_ex4pm_#{spec.algorithm_id}_replay_v1"
      assert spec.module.supports?(spec.algorithm_id, [])
    end
  end

  test "every spec standing is a rung of the 10-state ladder (found among DERIVED)" do
    for spec <- AlgoRegistry.algo_specs(), do: assert(spec.standing in @ladder)
  end

  test "every adapter module on disk is registered (registration is not the module count)" do
    on_disk =
      "lib/ex4pm_engine/wasm/*.ex"
      |> Path.wildcard()
      |> Enum.filter(&(File.read!(&1) =~ ~r/^\s*use Ex4pmEngine\.Wasm\.Adapter,/m))
      |> Enum.map(&(&1 |> Path.basename(".ex") |> String.to_atom()))
      |> Enum.sort()

    assert on_disk == Enum.sort(AlgoRegistry.algorithm_ids())
  end

  test "registry agrees with RealTransport.algo_specs/0 on module and export names" do
    take = &Map.take(&1, [:module, :algorithm_id, :export_name, :replay_export_name])

    assert AlgoRegistry.algo_specs() |> Enum.map(take) |> Enum.sort_by(& &1.algorithm_id) ==
             RealTransport.algo_specs() |> Enum.map(take) |> Enum.sort_by(& &1.algorithm_id)
  end
end
