# GENERATED by ggen_igniter from the admitted ex4pmb:AdmittedBeam4pmService graph. Do not edit.
defmodule Engine.Beam4pmTest do
  use ExUnit.Case, async: false

  # Real, no-mock tests. The happy-path/route-table/availability tests run
  # against test/support/micro_beam4pm.ex -- a REAL Ash resource + real
  # AshJsonApi.Router (Ash.DataLayer.Ets, no database needed), so this
  # suite validates Ex4pm.Engine.Beam4pm's request/response contract
  # against the actual AshJsonApi wire format (real route shape, real
  # JSON:API response envelope) instead of a hand-guessed fake -- the
  # same library beam4pm's own future json_api exposure
  # (docs/BEAM4PM-OPENAPI-GGEN-IGNITER-PLAN.md) will use. A handful of
  # error-injection scenarios a real Ash resource can't easily be coerced
  # into producing (a bare 500, a non-JSON-object 2xx body, an
  # unresponsive server) still use small, purpose-built single-behavior
  # Plug.Router fakes below -- each real, no mocking library involved.
  #
  # Real, currently admitted routes this generated test suite covers:
  #
    #   * `GET /conformance_result` (action `read`, informational only -- not sent over the wire) -> `:beam4pm_conformance_results`
  #   * `GET /ocel_event` (action `read`, informational only -- not sent over the wire) -> `:beam4pm_ocel_events`

  alias Ex4pm.Engine.Beam4pm

  defmodule ErrorRouter do
    use Plug.Router
    plug(:match)
    plug(:dispatch)

    get "/conformance_result" do
      conn
      |> Plug.Conn.put_resp_content_type("application/json")
      |> Plug.Conn.send_resp(500, Jason.encode!(%{"error" => "boom"}))
    end
  end

  defmodule InvalidBodyRouter do
    use Plug.Router
    plug(:match)
    plug(:dispatch)

    get "/ocel_event" do
      # A real 2xx response whose decoded body is a JSON array, not an
      # object -- exercises the beam4pm_invalid_response refusal branch.
      conn
      |> Plug.Conn.put_resp_content_type("application/json")
      |> Plug.Conn.send_resp(200, Jason.encode!([1, 2, 3]))
    end
  end

  defmodule SlowRouter do
    use Plug.Router
    plug(:match)
    plug(:dispatch)

    get "/ocel_event" do
      # Sleeps far longer than any client receive_timeout under test -- a
      # real unresponsive server, not a simulated one.
      Process.sleep(3_000)

      conn
      |> Plug.Conn.put_resp_content_type("application/json")
      |> Plug.Conn.send_resp(200, Jason.encode!(%{"data" => []}))
    end
  end

  defp start_router!(plug) do
    port = Enum.random(20_000..29_999)
    {:ok, pid} = Bandit.start_link(plug: plug, port: port, ip: {127, 0, 0, 1})
    on_exit(fn -> Process.exit(pid, :normal) end)
    "http://127.0.0.1:#{port}"
  end

  setup do
    {:ok, base_url: start_router!(MicroBeam4pm.Router)}
  end

  test "id/0 and the ontology-admitted route table (one assertion per admitted operation, generated)" do
    assert Beam4pm.id() == :beam4pm
    assert Beam4pm.supports?(:beam4pm_conformance_results, [])
    assert Beam4pm.supports?(:beam4pm_ocel_events, [])
    refute Beam4pm.supports?(:not_an_admitted_operation, [])
  end

  test "available?/1 requires a configured base_url" do
    refute Beam4pm.available?([])
    assert Beam4pm.available?(beam4pm_base_url: "http://127.0.0.1:1")
  end

  test "a real successful request against a real AshJsonApi server reaches :alive standing", %{base_url: base_url} do
    # Real JSON:API spec requirement, confirmed the hard way: a write
    # request needs the `application/vnd.api+json` media type, not plain
    # `application/json`, or AshJsonApi refuses it as 415 Unsupported
    # Media Type.
    seed_response =
      Req.post!(base_url <> "/ocel_event",
        headers: [{"content-type", "application/vnd.api+json"}],
        json: %{"data" => %{"type" => "ocel_event", "attributes" => %{"activity" => "commit_qualified"}}}
      )

    %{"data" => %{"id" => id}} = seed_response.body

    {:ok, result} = Beam4pm.execute(:beam4pm_ocel_events, %{id: id}, beam4pm_base_url: base_url)

    assert result.engine == :beam4pm
    assert [%{"id" => ^id}] = result.value
    # A real AshJsonApi response has no top-level "meta.source_sha"/
    # "receipt_verified" -- beam4pm doesn't emit those fields (this
    # engine's identity/receipt evidence is a forward-declared beam4pm
    # capability, not something AshJsonApi provides natively), so standing
    # correctly stays :partial_alive rather than a falsely-claimed :alive.
    assert result.standing == :partial_alive
    assert result.evidence.beam4pm_identity == nil
  end

  test "an unadmitted operation is refused, never silently attempted", %{base_url: base_url} do
    assert {:error, refusal} = Beam4pm.execute(:not_an_admitted_operation, %{}, beam4pm_base_url: base_url)
    assert refusal.code == :beam4pm_unsupported_operation
  end

  test "no configured base_url is refused as unavailable, not a crash" do
    assert {:error, refusal} = Beam4pm.execute(:beam4pm_ocel_events, %{id: "e1"}, [])
    assert refusal.code == :beam4pm_unavailable
  end

  test "a real non-2xx response from a real server is refused with the real status" do
    base_url = start_router!(ErrorRouter)

    assert {:error, refusal} =
             Beam4pm.execute(:beam4pm_conformance_results, %{id: "c1"}, beam4pm_base_url: base_url)

    assert refusal.code == :beam4pm_http_error
    assert refusal.details.status == 500
  end

  test "a real connection failure (server not listening) is refused as unavailable" do
    assert {:error, refusal} =
             Beam4pm.execute(:beam4pm_ocel_events, %{id: "e1"}, beam4pm_base_url: "http://127.0.0.1:1")

    assert refusal.code == :beam4pm_unavailable
  end

  test "a real 2xx response whose decoded body is a JSON array (not an object) is refused as invalid, not treated as data" do
    base_url = start_router!(InvalidBodyRouter)

    assert {:error, refusal} =
             Beam4pm.execute(:beam4pm_ocel_events, %{id: "non-object-body-trigger"}, beam4pm_base_url: base_url)

    assert refusal.code == :beam4pm_invalid_response
    assert refusal.details.status == 200
  end

  test "available?/1 also honors a base_url configured via Application.get_env, not just opts" do
    refute Beam4pm.available?([])

    Application.put_env(:ex4pm, :beam4pm_base_url, "http://127.0.0.1:1")

    on_exit(fn -> Application.delete_env(:ex4pm, :beam4pm_base_url) end)

    assert Beam4pm.available?([])
  end

  test "execute/3 also resolves base_url from Application.get_env when opts omit it", %{base_url: base_url} do
    Application.put_env(:ex4pm, :beam4pm_base_url, base_url)
    on_exit(fn -> Application.delete_env(:ex4pm, :beam4pm_base_url) end)

    assert {:ok, result} = Beam4pm.execute(:beam4pm_ocel_events, %{id: "e1"}, [])
    # Not asserting emptiness: Ash.DataLayer.Ets is a real, process-shared
    # in-memory table with no automatic reset between tests in this suite
    # (async: false, but ETS persists across test cases in the same run)
    # -- a genuinely correct assertion here is "this really is a JSON:API
    # index response," not "it's empty," since another test may have
    # already created a real record.
    assert is_list(result.value)
  end

  test "a real slow/unresponsive server is refused as a bounded timeout, not left to hang forever" do
    # Real regression coverage for a real bug found by adversarial audit:
    # earlier, `request/6` never passed `receive_timeout` to Req, so this
    # exact scenario (a real server that never responds) hung the caller
    # indefinitely instead of ever reaching the `:beam4pm_timeout` refusal
    # branch. The slow endpoint here sleeps far longer than the configured
    # client timeout, so this test would itself time out and fail (not
    # hang the suite forever, ExUnit still bounds the test) if the bug
    # ever regressed.
    base_url = start_router!(SlowRouter)

    {elapsed_us, result} =
      :timer.tc(fn ->
        Beam4pm.execute(:beam4pm_ocel_events, %{id: "e1"},
          beam4pm_base_url: base_url,
          beam4pm_receive_timeout: 200
        )
      end)

    assert {:error, refusal} = result
    assert refusal.code == :beam4pm_timeout
    # Real bound: must resolve near the configured 200ms timeout, never
    # anywhere near the fake server's multi-second sleep.
    assert elapsed_us < 2_000_000
  end
end
