# GENERATED by ggen_igniter from the admitted ex4pmsc:AdmittedStandingCode graph. Do not edit.
defmodule Ex4pm.Standing.CodedTest do
  use ExUnit.Case, async: true

  alias Ex4pm.Standing.Coded

  test "round-trips the real production example ALIVE[WS3_CHICAGO_MERGE_50]" do
    coded = Coded.new(:alive, "WS3_CHICAGO_MERGE_50")
    assert Coded.to_string(coded) == "ALIVE[WS3_CHICAGO_MERGE_50]"
    assert Coded.parse("ALIVE[WS3_CHICAGO_MERGE_50]") == {:ok, coded}
  end


  test "round-trips the real production example ALIVE[WS3_FORTUNE5_RUNTIME_VALUE_50]" do
    coded = Coded.new(:alive, "WS3_FORTUNE5_RUNTIME_VALUE_50")
    assert Coded.to_string(coded) == "ALIVE[WS3_FORTUNE5_RUNTIME_VALUE_50]"
    assert Coded.parse("ALIVE[WS3_FORTUNE5_RUNTIME_VALUE_50]") == {:ok, coded}
  end


  test "round-trips the real production example BUILD_BROKEN[TAKT_SHORTFALL]" do
    coded = Coded.new(:build_broken, "TAKT_SHORTFALL")
    assert Coded.to_string(coded) == "BUILD_BROKEN[TAKT_SHORTFALL]"
    assert Coded.parse("BUILD_BROKEN[TAKT_SHORTFALL]") == {:ok, coded}
  end


  test "round-trips the real production example PARTIAL_ALIVE[MERGED_LOCAL_CAPSULE_NAMESPACE_UNAVAILABLE]" do
    coded = Coded.new(:partial_alive, "MERGED_LOCAL_CAPSULE_NAMESPACE_UNAVAILABLE")
    assert Coded.to_string(coded) == "PARTIAL_ALIVE[MERGED_LOCAL_CAPSULE_NAMESPACE_UNAVAILABLE]"
    assert Coded.parse("PARTIAL_ALIVE[MERGED_LOCAL_CAPSULE_NAMESPACE_UNAVAILABLE]") == {:ok, coded}
  end

  test "bare standing (no code) renders and parses without brackets" do
    coded = Coded.new(:alive)
    assert Coded.to_string(coded) == "ALIVE"
    assert Coded.parse("ALIVE") == {:ok, coded}
  end

  test "parse/1 refuses a malformed string, never crashes" do
    assert Coded.parse("not a valid standing string!!!") == :error
  end

  test "rank/1 dispatches through Ex4pm.Standing.rank/1 for both bare atoms and coded structs" do
    coded = Coded.new(:alive, "SOME_CODE")
    assert Coded.rank(coded) == Ex4pm.Standing.rank(:alive)
    assert Coded.rank(:alive) == Ex4pm.Standing.rank(:alive)
  end

  test "min/2 picks the lower-ranked of two coded standings, keeping its own code" do
    blocked = Coded.new(:blocked, "SOME_CODE")
    alive = Coded.new(:alive, "OTHER_CODE")
    assert Coded.min(blocked, alive) == blocked
  end
end
