# GENERATED by ggen_igniter from the admitted ex4pmal:RegisteredAlgorithm graph. Do not edit.
defmodule Ex4pmEngine.Wasm.AlgoRegistry do
  @moduledoc """
  Generated registry of the 33 WASM-backed algorithm adapters.

  Source of truth: `epm:AlgorithmBinding` individuals in the vendored
  `ex4pm-wasm4pm-bindings-pack` plus one `ex4pmal:RegisteredAlgorithm` per
  algorithm in `priv/ontology/ex4pm.ttl`, merged by
  `mix ex4pm.ggen.sync` (unit `algo_registry`). To add or change an entry,
  edit the ontology/pack and re-run the sync; see
  `docs/ALGORITHM-REGISTRY-GENERATION.md`.

  Each spec carries the evidentiary `standing` rung (name of one of the 10
  `standing-ladder-pack` states, as a string) the registration is gated at.
  It is NOT an `Ex4pm.Standing` atom and is deliberately unmapped to it.
  """

  @type spec :: %{
          module: module(),
          algorithm_id: atom(),
          export_name: String.t(),
          replay_export_name: String.t(),
          standing: String.t()
        }

  @specs [
    %{
      module: Ex4pmEngine.Wasm.Align,
      algorithm_id: :align,
      export_name: "wasm4pm_ex4pm_align_v1",
      replay_export_name: "wasm4pm_ex4pm_align_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.AllenTemporal,
      algorithm_id: :allen_temporal,
      export_name: "wasm4pm_ex4pm_allen_temporal_v1",
      replay_export_name: "wasm4pm_ex4pm_allen_temporal_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Bayesian,
      algorithm_id: :bayesian,
      export_name: "wasm4pm_ex4pm_bayesian_v1",
      replay_export_name: "wasm4pm_ex4pm_bayesian_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Conform,
      algorithm_id: :conform,
      export_name: "wasm4pm_ex4pm_conform_v1",
      replay_export_name: "wasm4pm_ex4pm_conform_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.CtlCheck,
      algorithm_id: :ctl_check,
      export_name: "wasm4pm_ex4pm_ctl_check_v1",
      replay_export_name: "wasm4pm_ex4pm_ctl_check_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Discover,
      algorithm_id: :discover,
      export_name: "wasm4pm_ex4pm_discover_v1",
      replay_export_name: "wasm4pm_ex4pm_discover_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.DotProduct,
      algorithm_id: :dot_product,
      export_name: "wasm4pm_ex4pm_dot_product_v1",
      replay_export_name: "wasm4pm_ex4pm_dot_product_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.EtcPrecision,
      algorithm_id: :etc_precision,
      export_name: "wasm4pm_ex4pm_etc_precision_v1",
      replay_export_name: "wasm4pm_ex4pm_etc_precision_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.EuclideanDistance,
      algorithm_id: :euclidean_distance,
      export_name: "wasm4pm_ex4pm_euclidean_distance_v1",
      replay_export_name: "wasm4pm_ex4pm_euclidean_distance_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Ewma,
      algorithm_id: :ewma,
      export_name: "wasm4pm_ex4pm_ewma_v1",
      replay_export_name: "wasm4pm_ex4pm_ewma_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Forecast,
      algorithm_id: :forecast,
      export_name: "wasm4pm_ex4pm_forecast_v1",
      replay_export_name: "wasm4pm_ex4pm_forecast_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.HoltForecast,
      algorithm_id: :holt_forecast,
      export_name: "wasm4pm_ex4pm_holt_forecast_v1",
      replay_export_name: "wasm4pm_ex4pm_holt_forecast_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.HtnPlan,
      algorithm_id: :htn_plan,
      export_name: "wasm4pm_ex4pm_htn_plan_v1",
      replay_export_name: "wasm4pm_ex4pm_htn_plan_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.KsCriticalValue,
      algorithm_id: :ks_critical_value,
      export_name: "wasm4pm_ex4pm_ks_critical_value_v1",
      replay_export_name: "wasm4pm_ex4pm_ks_critical_value_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.KsStatistic,
      algorithm_id: :ks_statistic,
      export_name: "wasm4pm_ex4pm_ks_statistic_v1",
      replay_export_name: "wasm4pm_ex4pm_ks_statistic_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Markov,
      algorithm_id: :markov,
      export_name: "wasm4pm_ex4pm_markov_v1",
      replay_export_name: "wasm4pm_ex4pm_markov_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Mean,
      algorithm_id: :mean,
      export_name: "wasm4pm_ex4pm_mean_v1",
      replay_export_name: "wasm4pm_ex4pm_mean_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Median,
      algorithm_id: :median,
      export_name: "wasm4pm_ex4pm_median_v1",
      replay_export_name: "wasm4pm_ex4pm_median_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.OcDiscover,
      algorithm_id: :oc_discover,
      export_name: "wasm4pm_ex4pm_oc_discover_v1",
      replay_export_name: "wasm4pm_ex4pm_oc_discover_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.OcpqEval,
      algorithm_id: :ocpq_eval,
      export_name: "wasm4pm_ex4pm_ocpq_eval_v1",
      replay_export_name: "wasm4pm_ex4pm_ocpq_eval_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Optimize,
      algorithm_id: :optimize,
      export_name: "wasm4pm_ex4pm_optimize_v1",
      replay_export_name: "wasm4pm_ex4pm_optimize_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Percentile,
      algorithm_id: :percentile,
      export_name: "wasm4pm_ex4pm_percentile_v1",
      replay_export_name: "wasm4pm_ex4pm_percentile_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Playout,
      algorithm_id: :playout,
      export_name: "wasm4pm_ex4pm_playout_v1",
      replay_export_name: "wasm4pm_ex4pm_playout_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.PowlMine,
      algorithm_id: :powl_mine,
      export_name: "wasm4pm_ex4pm_powl_mine_v1",
      replay_export_name: "wasm4pm_ex4pm_powl_mine_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.PrologQuery,
      algorithm_id: :prolog_query,
      export_name: "wasm4pm_ex4pm_prolog_query_v1",
      replay_export_name: "wasm4pm_ex4pm_prolog_query_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Regression,
      algorithm_id: :regression,
      export_name: "wasm4pm_ex4pm_regression_v1",
      replay_export_name: "wasm4pm_ex4pm_regression_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Simulate,
      algorithm_id: :simulate,
      export_name: "wasm4pm_ex4pm_simulate_v1",
      replay_export_name: "wasm4pm_ex4pm_simulate_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Soundness,
      algorithm_id: :soundness,
      export_name: "wasm4pm_ex4pm_soundness_v1",
      replay_export_name: "wasm4pm_ex4pm_soundness_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Standardize,
      algorithm_id: :standardize,
      export_name: "wasm4pm_ex4pm_standardize_v1",
      replay_export_name: "wasm4pm_ex4pm_standardize_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.StdDeviation,
      algorithm_id: :std_deviation,
      export_name: "wasm4pm_ex4pm_std_deviation_v1",
      replay_export_name: "wasm4pm_ex4pm_std_deviation_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.StripsPlan,
      algorithm_id: :strips_plan,
      export_name: "wasm4pm_ex4pm_strips_plan_v1",
      replay_export_name: "wasm4pm_ex4pm_strips_plan_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.Survival,
      algorithm_id: :survival,
      export_name: "wasm4pm_ex4pm_survival_v1",
      replay_export_name: "wasm4pm_ex4pm_survival_replay_v1",
      standing: "DERIVED"
    },
    %{
      module: Ex4pmEngine.Wasm.TrendClassify,
      algorithm_id: :trend_classify,
      export_name: "wasm4pm_ex4pm_trend_classify_v1",
      replay_export_name: "wasm4pm_ex4pm_trend_classify_replay_v1",
      standing: "DERIVED"
    }
  ]

  @doc "All registered algorithms, ordered by `algorithm_id`."
  @spec algo_specs() :: [spec()]
  def algo_specs, do: @specs

  @doc "All registered `algorithm_id` atoms, in registry order."
  @spec algorithm_ids() :: [atom()]
  def algorithm_ids, do: Enum.map(@specs, & &1.algorithm_id)

  @engine_ranks [
    {Ex4pmEngine.Wasm.Discover, 0},
    {Ex4pmEngine.Wasm.Conform, 1},
    {Ex4pmEngine.Wasm.Simulate, 2},
    {Ex4pmEngine.Wasm.Optimize, 3},
    {Ex4pmEngine.Wasm.PowlMine, 4},
    {Ex4pmEngine.Wasm.Survival, 5},
    {Ex4pmEngine.Wasm.Markov, 6},
    {Ex4pmEngine.Wasm.Bayesian, 7},
    {Ex4pmEngine.Wasm.OcpqEval, 8},
    {Ex4pmEngine.Wasm.StripsPlan, 9},
    {Ex4pmEngine.Wasm.HtnPlan, 10},
    {Ex4pmEngine.Wasm.CtlCheck, 11},
    {Ex4pmEngine.Wasm.AllenTemporal, 12},
    {Ex4pmEngine.Wasm.Align, 13},
    {Ex4pmEngine.Wasm.EtcPrecision, 14},
    {Ex4pmEngine.Wasm.Soundness, 15},
    {Ex4pmEngine.Wasm.Playout, 16},
    {Ex4pmEngine.Wasm.OcDiscover, 17},
    {Ex4pmEngine.Wasm.PrologQuery, 18},
    {Ex4pmEngine.Wasm.Mean, 19},
    {Ex4pmEngine.Wasm.Median, 20},
    {Ex4pmEngine.Wasm.Percentile, 21},
    {Ex4pmEngine.Wasm.StdDeviation, 22},
    {Ex4pmEngine.Wasm.Standardize, 23},
    {Ex4pmEngine.Wasm.DotProduct, 24},
    {Ex4pmEngine.Wasm.EuclideanDistance, 25},
    {Ex4pmEngine.Wasm.KsStatistic, 26},
    {Ex4pmEngine.Wasm.KsCriticalValue, 27},
    {Ex4pmEngine.Wasm.Regression, 28},
    {Ex4pmEngine.Wasm.Forecast, 29},
    {Ex4pmEngine.Wasm.HoltForecast, 30},
    {Ex4pmEngine.Wasm.Ewma, 31},
    {Ex4pmEngine.Wasm.TrendClassify, 32}
  ]

  @doc """
  Adapter modules paired with their explicit `Ex4pm.Engine.Registry`
  selection rank (from `ex4pmal:engineRank`), ordered by ascending rank.
  """
  @spec engine_ranks() :: [{module(), non_neg_integer()}]
  def engine_ranks, do: @engine_ranks

  @doc "Adapter modules in engine-registry rank order."
  @spec engine_modules() :: [module()]
  def engine_modules, do: Enum.map(@engine_ranks, &elem(&1, 0))
end
