# GENERATED by ggen_igniter from the admitted ex4pmb:AdmittedBeam4pmService graph. Do not edit.
defmodule Ex4pm.Engine.Beam4pm do
  @moduledoc """
  Zero-config beam4pm engine candidate: connects to beam4pm as a generic
  Ash JSON:API client. "Zero config" means the ROUTE TABLE below is
  entirely admitted-ontology data (`priv/ontology/ex4pm.ttl`'s
  `ex4pmb:AdmittedBeam4pmService` graph) -- adding a new operation this
  engine can reach is a new ontology individual plus `mix ex4pm.ggen.sync`,
  never new hand-written dispatch code. See
  `docs/EX4PM-THINNING-BEAM4PM-ENRICHMENT.md` for the full migration this
  serves.

  Configure with `beam4pm_base_url: "http://host:port"` in opts (or
  `Application.put_env(:ex4pm, :beam4pm_base_url, ...)`). No per-operation
  configuration is needed or accepted -- the route table is fixed at
  generation time from the ontology.

  Admitted operations this engine currently supports:

      * `:beam4pm_conformance_results` -> `GET /conformance_result` (action `read`)
    * `:beam4pm_ocel_events` -> `GET /ocel_event` (action `read`)

  ## Honest status

  As of this generation, beam4pm does not yet mount a live AshJsonApi
  router (see the `ex4pmb:` prefix comment in `priv/ontology/ex4pm.ttl`
  for the exact verification). This module's HTTP mechanics are real and
  tested against a real local JSON:API-shaped server
  (`test/engine_beam4pm_test.exs`); connecting it to a real beam4pm
  instance is gated on that separate, disclosed prerequisite.
  """
  @behaviour Ex4pm.Engine

  alias Ex4pm.Engine.Result
  alias Ex4pm.Refusal

  @route_table %{
    :beam4pm_conformance_results => %{json_api_type: "conformance_result", action: "read", http_method: :get},
    :beam4pm_ocel_events => %{json_api_type: "ocel_event", action: "read", http_method: :get}
  }

  @impl true
  def id, do: :beam4pm

  @impl true
  def supports?(operation, _opts), do: Map.has_key?(@route_table, operation)

  @impl true
  def available?(opts) do
    supports_any? = map_size(@route_table) > 0
    supports_any? and is_binary(base_url(opts))
  end

  @impl true
  def execute(operation, subject, opts) do
    with %{json_api_type: type, action: action, http_method: method} <-
           Map.get(@route_table, operation) ||
             {:error,
              Refusal.new(:beam4pm_unsupported_operation, "beam4pm has no admitted route for this operation",
                details: %{operation: operation}
              )},
         base when is_binary(base) <-
           base_url(opts) ||
             {:error,
              Refusal.new(:beam4pm_unavailable, "no beam4pm_base_url configured", details: %{operation: operation})},
         {:ok, response} <- request(base, type, action, method, subject, opts) do
      {:ok,
       %Result{
         engine: :beam4pm,
         operation: operation,
         algorithm: :ash_json_api,
         subject_hash: Ex4pm.Core.Hash.digest(subject),
         standing: standing_for(response),
         value: Map.get(response, "data"),
         evidence: %{
           executed: true,
           transport: :https,
           json_api_type: type,
           action: action,
           http_method: method,
           beam4pm_identity: identity_from(response)
         }
       }}
    end
  end

  defp base_url(opts) do
    Keyword.get(opts, :beam4pm_base_url) || Application.get_env(:ex4pm, :beam4pm_base_url)
  end

  defp request(base, type, action, method, subject, opts) do
    http_module = Keyword.get(opts, :beam4pm_http_module, Req)
    url = Path.join(base, "/#{type}")
    query = %{"action" => action, "subject_hash" => Ex4pm.Core.Hash.digest(subject)}

    result =
      case method do
        :get -> http_module.get(url, params: query, retry: false)
        :post -> http_module.post(url, json: query, retry: false)
      end

    case result do
      {:ok, %{status: status, body: body}} when status in 200..299 and is_map(body) ->
        {:ok, body}

      {:ok, %{status: status, body: body}} when status in 200..299 ->
        {:error,
         Refusal.new(:beam4pm_invalid_response, "beam4pm returned a 2xx status but a non-JSON-object body",
           details: %{status: status, url: url, body: inspect(body)}
         )}

      {:ok, %{status: status}} ->
        {:error,
         Refusal.new(:beam4pm_http_error, "beam4pm returned a non-2xx status",
           details: %{status: status, url: url}
         )}

      {:error, %{reason: :timeout}} ->
        {:error, Refusal.new(:beam4pm_timeout, "beam4pm request timed out", details: %{url: url})}

      {:error, reason} ->
        {:error, Refusal.new(:beam4pm_unavailable, "beam4pm request failed", details: %{url: url, reason: inspect(reason)})}
    end
  end

  defp standing_for(response) do
    if identity_from(response) do
      :alive
    else
      :partial_alive
    end
  end

  defp identity_from(%{"meta" => %{"source_sha" => sha, "receipt_verified" => true}}) when is_binary(sha) do
    %{source_sha: sha, receipt_verified: true}
  end

  defp identity_from(_response), do: nil
end
