apiVersion: v1
kind: Secret
metadata:
  name: ex4pm-secrets
type: Opaque
stringData:
  SECRET_KEY_BASE: "n8QG9v7W8zmrj2kg5sfn9aqmcac8pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5"
  RELEASE_COOKIE: "ex4pm_cluster_secret_cookie_26_8_23"
  DATABASE_URL: "ecto://postgres:postgres@postgres:5432/ex4pm_prod"
  POSTGRES_PASSWORD: "postgres_cluster_password_secure"
