apiVersion: v1
kind: Service
metadata:
  name: ex4pm
  labels:
    app: ex4pm
spec:
  type: NodePort
  selector:
    app: ex4pm
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
