if Code.ensure_loaded?(Igniter.Mix.Task) do
  defmodule Mix.Tasks.Ex4pm.Engine.Gen.Adapter do
    @moduledoc """
    Generates a new WASM adapter module for `Ex4pm.Engine.Wasm`, following the
    exact pattern established by `Ex4pmEngine.Wasm.Mean`.

        mix ex4pm.engine.gen.adapter <algorithm_id>

    Creates `apps/ex4pm_engine/lib/ex4pm_engine/wasm/<algorithm_id>.ex` defining
    `Ex4pmEngine.Wasm.<CamelizedAlgorithmId>`, a thin per-algorithm wrapper that
    names the admitted export symbol (defaulted to the algorithm id itself) and
    delegates real execution to `Ex4pm.Engine.Wasm.execute/3`.
    """

    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :ex4pm,
        example: "mix ex4pm.engine.gen.adapter median",
        positional: [:algorithm_id],
        schema: [export: :string],
        defaults: [export: nil]
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      %{algorithm_id: algorithm_id_arg} = igniter.args.positional
      export = igniter.args.options[:export] || algorithm_id_arg

      algorithm_id = algorithm_id_arg
      module_suffix = Macro.camelize(algorithm_id)
      module_name = Module.concat([Ex4pmEngine, Wasm, module_suffix])
      path = "lib/ex4pm_engine/wasm/#{algorithm_id}.ex"

      contents = adapter_body(algorithm_id, export)

      Igniter.Project.Module.create_module(igniter, module_name, contents, path: path)
    end

    defp adapter_body(algorithm_id, export) do
      """
      @moduledoc \"\"\"
      WASM adapter for the `:#{algorithm_id}` algorithm.

      Generated by `mix ex4pm.engine.gen.adapter #{algorithm_id}`, following the
      pattern established by `Ex4pmEngine.Wasm.Mean`.
      \"\"\"

      @algorithm_id :#{algorithm_id}
      @export #{inspect(export)}

      @spec algorithm_id() :: atom()
      def algorithm_id, do: @algorithm_id

      @spec export() :: String.t()
      def export, do: @export

      @doc \"\"\"
      Execute the `:#{algorithm_id}` algorithm against a configured, admitted
      WASM artifact via `Ex4pm.Engine.Wasm.execute/3`.
      \"\"\"
      @spec execute(term(), keyword()) :: {:ok, Ex4pm.Engine.Result.t()} | {:error, Ex4pm.Refusal.t()}
      def execute(subject, opts) do
        contract = Keyword.get(opts, :wasm_contract, %{})
        contract = Map.put(contract, @algorithm_id, Map.get(contract, @algorithm_id, %{}))
        contract = put_in(contract[@algorithm_id][:export], @export)
        contract = put_in(contract[@algorithm_id][:algorithm], @algorithm_id)

        opts = Keyword.put(opts, :wasm_contract, contract)
        Ex4pm.Engine.Wasm.execute(@algorithm_id, subject, opts)
      end
      """
    end
  end
else
  defmodule Mix.Tasks.Ex4pm.Engine.Gen.Adapter do
    @moduledoc """
    Generates a new WASM adapter module for `Ex4pm.Engine.Wasm` (requires `:igniter`).

    This task depends on the `:igniter` dependency, which is scoped to
    `only: [:dev, :test]` in `apps/ex4pm_engine/mix.exs`. It is unavailable
    outside those environments (e.g. `MIX_ENV=prod`).
    """

    use Mix.Task

    @impl Mix.Task
    def run(_argv) do
      Mix.raise("""
      mix ex4pm.engine.gen.adapter requires the :igniter dependency, which is only \
      available in :dev and :test environments. Run this task with MIX_ENV=dev or \
      MIX_ENV=test.
      """)
    end
  end
end
