PREFIX esf: <https://ggen.dev/ontology/epistemic-sensor-factory#>
ASK {
  esf:ex4pmR58Consumer esf:candidateRepo <https://github.com/seanchatmangpt/ex4pm> ;
    esf:candidateHead "e12fccb42a67bc4496cac91c86bff2b856cc463d" .
}
