# GENERATED by ggen_igniter from the admitted ex4pmsc:AdmittedStandingCode graph. Do not edit.
defmodule Ex4pm.Standing.Coded do
  @moduledoc """
  Reason-coded standing: `%Ex4pm.Standing.Coded{standing: atom(), code:
  String.t() | nil}`, rendering as the real `STANDING[REASON_CODE]` shape
  observed in production beam4pm scheduled-task receipts (see
  `docs/PRD-v26.9.10.md`) -- e.g. `ALIVE[WS3_CHICAGO_MERGE_50]`. Does not
  replace bare-atom `Ex4pm.Standing`; both stay valid, this is additive
  for callers that need a reason payload.

  `new/2`/`to_string/1`/`parse/1` are generic -- they work for any real
  `atom()` standing and any `String.t()` code, not just the examples
  below. What IS admission-fact-driven here is the real set of example
  `STANDING[CODE]` strings this module's own generated test suite
  round-trips (grown by adding a new `ex4pmsc:AdmittedStandingCode`
  individual to `priv/ontology/ex4pm.ttl` and re-running
  `scripts/standing_coded_sync.sh` -- no hand-written Elixir change
  needed to add real-world round-trip coverage):

      * `ALIVE[WS3_CHICAGO_MERGE_50]`
    * `ALIVE[WS3_FORTUNE5_RUNTIME_VALUE_50]`
    * `BUILD_BROKEN[TAKT_SHORTFALL]`
    * `PARTIAL_ALIVE[MERGED_LOCAL_CAPSULE_NAMESPACE_UNAVAILABLE]`
  """

  @enforce_keys [:standing]
  defstruct [:standing, code: nil]

  @type t :: %__MODULE__{standing: atom(), code: String.t() | nil}

  @doc "Builds a coded standing from a bare `Ex4pm.Standing`-shaped atom and an optional reason code."
  @spec new(atom(), String.t() | nil) :: t()
  def new(standing, code \\ nil) when is_atom(standing) and (is_binary(code) or is_nil(code)) do
    %__MODULE__{standing: standing, code: code}
  end

  @doc """
  Renders `STANDING[CODE]` (upcased standing, code verbatim), or just
  `STANDING` when `code` is `nil`.
  """
  @spec to_string(t()) :: String.t()
  def to_string(%__MODULE__{standing: standing, code: nil}) do
    standing |> Atom.to_string() |> String.upcase()
  end

  def to_string(%__MODULE__{standing: standing, code: code}) do
    (standing |> Atom.to_string() |> String.upcase()) <> "[" <> code <> "]"
  end

  @doc """
  Parses a real `STANDING[CODE]`-or-bare-`STANDING` string back into
  `{:ok, t()}`, or `:error` if the input doesn't match either shape.
  Round-trips every string `to_string/1` can produce.
  """
  @spec parse(String.t()) :: {:ok, t()} | :error
  def parse(str) when is_binary(str) do
    case Regex.run(~r/\A([A-Z0-9_]+)(?:\[([^\]]*)\])?\z/, str) do
      [_, standing_str] ->
        {:ok, new(standing_str |> String.downcase() |> String.to_atom())}

      [_, standing_str, code] ->
        {:ok, new(standing_str |> String.downcase() |> String.to_atom(), code)}

      nil ->
        :error
    end
  end

  @doc "Rank/min dispatch: accepts a bare atom or a coded struct, via its `.standing` field."
  @spec rank(atom() | t()) :: non_neg_integer()
  def rank(%__MODULE__{standing: standing}), do: Ex4pm.Standing.rank(standing)
  def rank(standing) when is_atom(standing), do: Ex4pm.Standing.rank(standing)

  @spec min(atom() | t(), atom() | t()) :: atom() | t()
  def min(%__MODULE__{} = left, %__MODULE__{} = right) do
    if rank(left) <= rank(right), do: left, else: right
  end

  def min(left, right), do: Ex4pm.Standing.min(left, right)
end
