defmodule Ex4pm.Standing.Coded do
  @moduledoc """
  GENERATED by `mix ex4pm.ggen.verify_determinism` / `Ex4pm.Ggen.Generator`.
  Source ontology: priv/ggen/units/standing_coded/ontology.ttl (sha256 ffef00313e81d5bbb5cc92588d0e81fcfc7351a2a83cdf42c882750e61451d59)
  Source queries: %{"standings" => "priv/ggen/units/standing_coded/standings.rq"} (sha256 9b30b1ea601589598b6c3d1df7a5409729cb34e8a9285eea1b187d32b5377b39)

  Do not hand-edit -- regenerate via `Ex4pm.Ggen.Generator.render/2` from the source
  ontology instead. This module exists so `mix ex4pm.ggen.verify_determinism` has a
  real generation unit to prove regeneration is byte-identical.
  """

  @standings [:UNKNOWN, :PARTIAL_ALIVE, :ALIVE, :BLOCKED, :BUILD_BROKEN, :UNSUPPORTED, :REFUSED]

  @doc "The typed evidence/standing vocabulary admitted by the ontology, as atoms."
  @spec standings() :: [atom()]
  def standings, do: @standings

  @doc "The ontology's sha256 this module was generated from, for drift detection."
  @spec ontology_hash() :: String.t()
  def ontology_hash, do: "ffef00313e81d5bbb5cc92588d0e81fcfc7351a2a83cdf42c882750e61451d59"
end
